Document: drinkduinogame
Title: Debian drinkduinogame Manual
Author: <insert document author here>
Abstract: This manual describes what drinkduinogame is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drinkduinogame/drinkduinogame.sgml.gz

Format: postscript
Files: /usr/share/doc/drinkduinogame/drinkduinogame.ps.gz

Format: text
Files: /usr/share/doc/drinkduinogame/drinkduinogame.text.gz

Format: HTML
Index: /usr/share/doc/drinkduinogame/html/index.html
Files: /usr/share/doc/drinkduinogame/html/*.html
